### ISSUE TITLE
Preprocessing is not defined?

### ISSUE THREAD

**Issue by gitlabspy** [SamArgt/AudioSourceSep#1]
Hi! I just found this wonderful repo.  When I tried to run some experiments upon it, I found `Preprocessing ` not defined. Should it be replaced by `ImgPreprocessing ` or `SpecPreprocessing `?
https://github.com/SamArgt/AudioSourceSep/blob/43fc0b2d9a63950b78fb19334e779d776f404708/flow_models/flow_flowpp.py#L93

**Comment by SamArgt** [comment]
Hi, it should be replaced by ImgPreprocessing if you want to run experiments on images. Just did it thanks!
